# Basic
title: So deep so quite
subtitle: footprint
welcome_message: <a href="https://github.com/ilake/vno-jekyll" target="_blank">Download the theme</a>
description: test for now.
creator: <a href="https://iclake.github.io">@iclake</a>

url: "https://iclake.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.ilake.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: ilake
    github: ilake
    twitter: ilake
    gplus: 107108267983477358170
    mail: onev@ilake.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
